---
- hosts: pi
  tasks:
    - synchronize:
        src: ../radio/
        dest: ~/radio/
        rsync_opts:
          - '--include=*.py'
          - '--include=server.properties'
          - '--include=sound/'
          - '--include=sound/radiotuning.ogg'
          - '--include=waveshare/'
          - '--include=waveshare/*.ttf'
          - '--exclude=*'
      notify: Restart Radio
    - name: Create service for radio
      become: yes
      copy:
        src: "../radio/francoisefm_radio.service"
        dest: "/etc/systemd/system"
      notify: Restart Radio
  handlers:
    - name: Restart Radio
      become: yes
      service:
        name: francoisefm_radio
        state: restarted