---
- hosts: pi
  tasks:
    - synchronize:
        src: ../radio/
        dest: ~/radio/
        rsync_opts:
          - '--include=*.py'
          - '--include=server.properties'
          - '--include=sound/'
          - '--include=sound/radiotuning.ogg'
          - '--include=waveshare/'
          - '--include=waveshare/*.ttf'
          - '--exclude=*'