---
- hosts: pi
  tasks:
    - synchronize:
        src: ../radio/
        dest: ~/radio/
        rsync_opts:
          - '--include=*.py'
          - '--include=server.properties'
          - '--include=static.wav'
          - '--include=waveshare/'
          - '--include=waveshare/*.ttf'
          - '--exclude=*'